# Generated by Django 4.1.4 on 2022-12-15 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('region', models.CharField(choices=[('Addis Ababa', 'አዲስ አበባ'), ('Diredawa', 'ድሬደዋ'), ('Oromia', 'ኦሮሚያ'), ('Amhara', 'አምራ'), ('Tigrai', 'ትግራይ'), ('Afar', 'አፋር'), ('Harari', 'ሀረሪ'), ('Sidama', 'ሲዳማ'), ('South Nations', 'ደቡብ ክልል'), ('Gambella', 'ጋምቤላ'), ('Benishangul Gumuz', 'ቤኒሻንጉል ጉሙዝ')], max_length=30)),
                ('town', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=300)),
                ('photo_1', models.ImageField(upload_to='home/')),
                ('photo_2', models.ImageField(upload_to='home/')),
                ('photo_3', models.ImageField(upload_to='home/')),
                ('photo_4', models.ImageField(upload_to='home/')),
                ('body', models.TextField()),
                ('category', models.CharField(choices=[('studio', 'ስቱድዮ'), ('apartment', 'አፓርታማ'), ('condominium', 'ኮንዶሚኒየም'), ('office', 'ቢሮ')], max_length=50)),
                ('rental_rate', models.IntegerField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='posts.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=250)),
                ('written_on', models.DateTimeField(auto_now_add=True)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='posts.post')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
